spring:
  application:
    name: mpos-service

server:
  port: ${SERVER_PORT:8083}

security:
  api-token: ${API_TOKEN:dev-secret-token}
  jwt-secret: ${JWT_SECRET:dev-jwt-secret-change-me-please-32-chars}

master-data-service:
  url: ${MASTER_DATA_SERVICE_URL:http://localhost:8084}
